#
# (c) 2024, Yegor Yakubovich, yegoryakubovich.com, personal@yegoryakybovich.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


version: '3.7'

services:
  api:
    build:
      dockerfile: api.dockerfile
    environment:
      MODULE_NAME: "api"
      MAX_WORKERS: 2
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./assets/texts_packs:/app/assets/texts_packs
      - ./assets/files:/app/assets/files
      - ./assets/telegram:/app/assets/telegram
    env_file:
      - .env
  bot:
    build:
      dockerfile: bot.dockerfile
    env_file:
      - .env
    depends_on:
      - api
  tasks_permanents:
    build:
      dockerfile: tasks_permanents.dockerfile
    volumes:
      - ./assets/texts_packs:/app/assets/texts_packs
      - ./assets/files:/app/assets/files
      - ./assets/telegram:/app/assets/telegram
    env_file:
      - .env
    depends_on:
      - api
#  tasks_celery:
#    build:
#      dockerfile: tasks_celery.dockerfile
#    volumes:
#      - ./app/tasks/:/app/app/tasks
#  tasks_flower:
#    environment:
#      FLOWER_BASIC_AUTH: ${FLOWER_USER}:${FLOWER_PASSWORD}
#    build:
#      dockerfile: tasks_flower.dockerfile
#    ports:
#      - "${TASKS_FLOWER_PORT}:5555"
