"""empty message

Revision ID: 04d9ce8a53b6
Revises: cdd206efba59
Create Date: 2024-07-30 17:15:15.254788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d9ce8a53b6'
down_revision: Union[str, None] = 'cdd206efba59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications_methods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('method_id', sa.BigInteger(), nullable=True),
    sa.Column('language_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_requisite', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notifications_histories', sa.Column('notification_method_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'notifications_histories', 'notifications_methods', ['notification_method_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications_histories', type_='foreignkey')
    op.drop_column('notifications_histories', 'notification_method_id')
    op.drop_table('notifications_methods')
    # ### end Alembic commands ###
