"""empty message

Revision ID: 1dd1fbb1857d
Revises: 4f3456b3243f
Create Date: 2024-07-22 19:35:19.184889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1dd1fbb1857d'
down_revision: Union[str, None] = '4f3456b3243f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rates_pairs', sa.Column('commission_pack_value_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('rates_pairs_ibfk_3', 'rates_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'rates_pairs', 'commissions_packs_values', ['commission_pack_value_id'], ['id'], ondelete='SET NULL')
    op.drop_column('rates_pairs', 'commission_pack_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rates_pairs', sa.Column('commission_pack_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rates_pairs', type_='foreignkey')
    op.create_foreign_key('rates_pairs_ibfk_3', 'rates_pairs', 'commissions_packs', ['commission_pack_id'], ['id'], ondelete='SET NULL')
    op.drop_column('rates_pairs', 'commission_pack_value_id')
    # ### end Alembic commands ###
