"""empty message

Revision ID: 26d834736632
Revises: 
Create Date: 2024-07-18 15:23:03.399078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d834736632'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_str', sa.String(length=16), nullable=True),
    sa.Column('decimal', sa.Integer(), nullable=True),
    sa.Column('rate_decimal', sa.Integer(), nullable=True),
    sa.Column('div', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_str', sa.String(length=32), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('extension', sa.String(length=8), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_str', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegrams_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.String(length=512), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('value_default', sa.String(length=1024), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timezones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_str', sa.String(length=16), nullable=True),
    sa.Column('deviation', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions_parameters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=256), nullable=True),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients_texts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('name_text_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['name_text_id'], ['texts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commissions_packs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_text_id', sa.BigInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['name_text_id'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_text_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['name_text_id'], ['texts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_str', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('language_default_id', sa.BigInteger(), nullable=True),
    sa.Column('timezone_default_id', sa.BigInteger(), nullable=True),
    sa.Column('currency_default_id', sa.BigInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['currency_default_id'], ['currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_default_id'], ['languages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timezone_default_id'], ['timezones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files_keys',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('methods',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('currency_id', sa.BigInteger(), nullable=True),
    sa.Column('name_text_id', sa.BigInteger(), nullable=True),
    sa.Column('schema_fields', sa.JSON(), nullable=True),
    sa.Column('schema_input_fields', sa.JSON(), nullable=True),
    sa.Column('input_rate_default', sa.Integer(), nullable=True),
    sa.Column('output_rate_default', sa.Integer(), nullable=True),
    sa.Column('input_rate_percent', sa.Integer(), nullable=True),
    sa.Column('output_rate_percent', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=8), nullable=True),
    sa.Column('bgcolor', sa.String(length=8), nullable=True),
    sa.Column('is_rate_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['name_text_id'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('id_str', sa.String(length=32), nullable=True),
    sa.Column('name_text_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['name_text_id'], ['texts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates_parsers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('currency_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('rate', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_text_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['name_text_id'], ['texts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texts_packs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('language_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texts_translations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text_id', sa.BigInteger(), nullable=True),
    sa.Column('language_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password_salt', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=32), nullable=True),
    sa.Column('firstname', sa.String(length=32), nullable=True),
    sa.Column('lastname', sa.String(length=32), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('language_id', sa.BigInteger(), nullable=True),
    sa.Column('timezone_id', sa.BigInteger(), nullable=True),
    sa.Column('currency_id', sa.BigInteger(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timezone_id'], ['timezones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commissions_packs_values',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('commission_pack_id', sa.BigInteger(), nullable=True),
    sa.Column('value_from', sa.BigInteger(), nullable=True),
    sa.Column('value_to', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('percent', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['commission_pack_id'], ['commissions_packs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('method_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('rate', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rates_pairs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('input_method_id', sa.BigInteger(), nullable=True),
    sa.Column('output_method_id', sa.BigInteger(), nullable=True),
    sa.Column('rate_decimal', sa.Integer(), nullable=True),
    sa.Column('rate', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['input_method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('permission_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('commission_pack_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('value_banned', sa.BigInteger(), nullable=True),
    sa.Column('value_can_minus', sa.BigInteger(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['commission_pack_id'], ['commissions_packs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_clients_texts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('client_text_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.String(length=2048), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_text_id'], ['clients_texts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_contacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('is_request', sa.Boolean(), nullable=True),
    sa.Column('is_requisite', sa.Boolean(), nullable=True),
    sa.Column('is_order', sa.Boolean(), nullable=True),
    sa.Column('is_chat', sa.Boolean(), nullable=True),
    sa.Column('is_transfer', sa.Boolean(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisites_datas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('method_id', sa.BigInteger(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('is_disposable', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('token_salt', sa.String(length=32), nullable=True),
    sa.Column('token_hash', sa.String(length=32), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('wallet_from_id', sa.BigInteger(), nullable=True),
    sa.Column('wallet_to_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_from_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_to_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets_bans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=16), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications_histories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('notification_setting_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['notification_setting_id'], ['notifications_settings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('wallet_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('rate_decimal', sa.Integer(), nullable=True),
    sa.Column('rate_fixed', sa.Boolean(), nullable=True),
    sa.Column('difference', sa.BigInteger(), nullable=True),
    sa.Column('difference_rate', sa.BigInteger(), nullable=True),
    sa.Column('commission', sa.BigInteger(), nullable=True),
    sa.Column('rate', sa.BigInteger(), nullable=True),
    sa.Column('input_method_id', sa.BigInteger(), nullable=True),
    sa.Column('output_requisite_data_id', sa.BigInteger(), nullable=True),
    sa.Column('output_method_id', sa.BigInteger(), nullable=True),
    sa.Column('input_currency_value', sa.BigInteger(), nullable=True),
    sa.Column('input_rate', sa.BigInteger(), nullable=True),
    sa.Column('input_value', sa.BigInteger(), nullable=True),
    sa.Column('output_value', sa.BigInteger(), nullable=True),
    sa.Column('output_rate', sa.BigInteger(), nullable=True),
    sa.Column('output_currency_value', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['input_method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_requisite_data_id'], ['requisites_datas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('state', sa.String(length=8), nullable=True),
    sa.Column('wallet_id', sa.BigInteger(), nullable=True),
    sa.Column('currency_id', sa.BigInteger(), nullable=True),
    sa.Column('input_method_id', sa.BigInteger(), nullable=True),
    sa.Column('output_requisite_data_id', sa.BigInteger(), nullable=True),
    sa.Column('output_method_id', sa.BigInteger(), nullable=True),
    sa.Column('currency_value', sa.BigInteger(), nullable=True),
    sa.Column('total_currency_value', sa.BigInteger(), nullable=True),
    sa.Column('rate', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('total_value', sa.BigInteger(), nullable=True),
    sa.Column('currency_value_min', sa.BigInteger(), nullable=True),
    sa.Column('currency_value_max', sa.BigInteger(), nullable=True),
    sa.Column('in_process', sa.Boolean(), nullable=True),
    sa.Column('is_flex', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['input_method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_method_id'], ['methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_requisite_data_id'], ['requisites_datas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers_systems',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('transfer_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('canceled_reason', sa.String(length=16), nullable=True),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('requisite_id', sa.BigInteger(), nullable=True),
    sa.Column('currency_value', sa.BigInteger(), nullable=True),
    sa.Column('rate', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.Column('requisite_scheme_fields', sa.JSON(), nullable=True),
    sa.Column('requisite_fields', sa.JSON(), nullable=True),
    sa.Column('input_scheme_fields', sa.JSON(), nullable=True),
    sa.Column('input_fields', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requisite_id'], ['requisites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests_requisites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('requisite_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requisite_id'], ['requisites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets_bans_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_ban_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_ban_id'], ['wallets_bans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets_bans_requisites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_ban_id', sa.BigInteger(), nullable=True),
    sa.Column('requisite_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['requisite_id'], ['requisites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_ban_id'], ['wallets_bans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=True),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_transfers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('transfer_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_files')
    op.drop_table('orders_transfers')
    op.drop_table('orders_requests')
    op.drop_table('orders_files')
    op.drop_table('messages')
    op.drop_table('wallets_bans_requisites')
    op.drop_table('wallets_bans_requests')
    op.drop_table('requests_requisites')
    op.drop_table('orders')
    op.drop_table('transfers_systems')
    op.drop_table('requisites')
    op.drop_table('requests')
    op.drop_table('notifications_histories')
    op.drop_table('wallets_bans')
    op.drop_table('wallets_accounts')
    op.drop_table('transfers')
    op.drop_table('sessions')
    op.drop_table('requisites_datas')
    op.drop_table('notifications_settings')
    op.drop_table('accounts_roles')
    op.drop_table('accounts_contacts')
    op.drop_table('accounts_clients_texts')
    op.drop_table('wallets')
    op.drop_table('roles_permissions')
    op.drop_table('rates_pairs')
    op.drop_table('rates')
    op.drop_table('commissions_packs_values')
    op.drop_table('accounts')
    op.drop_table('texts_translations')
    op.drop_table('texts_packs')
    op.drop_table('roles')
    op.drop_table('rates_parsers')
    op.drop_table('permissions')
    op.drop_table('methods')
    op.drop_table('files_keys')
    op.drop_table('countries')
    op.drop_table('contacts')
    op.drop_table('commissions_packs')
    op.drop_table('clients_texts')
    op.drop_table('actions_parameters')
    op.drop_table('timezones')
    op.drop_table('texts')
    op.drop_table('telegrams_posts')
    op.drop_table('languages')
    op.drop_table('files')
    op.drop_table('currencies')
    op.drop_table('actions')
    # ### end Alembic commands ###
