"""empty message

Revision ID: 59449b41d7d9
Revises: a97b8ddc8db5
Create Date: 2024-07-30 22:19:33.005023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59449b41d7d9'
down_revision: Union[str, None] = 'a97b8ddc8db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications_methods', 'is_requisite')
    op.drop_column('notifications_methods', 'is_system')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_methods', sa.Column('is_system', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('notifications_methods', sa.Column('is_requisite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
