"""empty message

Revision ID: 8733b0b21b8e
Revises: cea2dd38e12b
Create Date: 2024-07-24 08:15:55.709591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8733b0b21b8e'
down_revision: Union[str, None] = 'cea2dd38e12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients_texts', sa.Column('type', sa.String(length=32), nullable=True))
    op.drop_column('telegrams_posts', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegrams_posts', sa.Column('text', mysql.VARCHAR(length=512), nullable=True))
    op.drop_column('clients_texts', 'type')
    # ### end Alembic commands ###
