"""empty message

Revision ID: 87d8a3f28533
Revises: a51a7af65d85
Create Date: 2024-07-18 17:11:38.611636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87d8a3f28533'
down_revision: Union[str, None] = 'a51a7af65d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commissions_packs', sa.Column('filename', sa.String(length=32), nullable=True))
    op.add_column('telegrams_posts', sa.Column('commission_pack_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'telegrams_posts', 'commissions_packs', ['commission_pack_id'], ['id'], ondelete='SET NULL')
    op.drop_column('telegrams_posts', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegrams_posts', sa.Column('chat_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'telegrams_posts', type_='foreignkey')
    op.drop_column('telegrams_posts', 'commission_pack_id')
    op.drop_column('commissions_packs', 'filename')
    # ### end Alembic commands ###
