"""empty message

Revision ID: 981f5948ca55
Revises: a71509f533c4
Create Date: 2024-07-26 17:48:29.746581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '981f5948ca55'
down_revision: Union[str, None] = 'a71509f533c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_settings', sa.Column('is_system', sa.Boolean(), nullable=True))
    op.drop_column('notifications_settings', 'is_global')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_settings', sa.Column('is_global', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('notifications_settings', 'is_system')
    # ### end Alembic commands ###
