"""empty message

Revision ID: a97b8ddc8db5
Revises: 04d9ce8a53b6
Create Date: 2024-07-30 22:10:41.284627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a97b8ddc8db5'
down_revision: Union[str, None] = '04d9ce8a53b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications_methods_histories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_method_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['notification_method_id'], ['notifications_methods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_methods_histories')
    # ### end Alembic commands ###
