"""empty message

Revision ID: c600f4ed5f11
Revises: 59449b41d7d9
Create Date: 2024-07-31 01:06:24.335415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c600f4ed5f11'
down_revision: Union[str, None] = '59449b41d7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notifications_histories_ibfk_2', 'notifications_histories', type_='foreignkey')
    op.drop_column('notifications_histories', 'notification_method_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_histories', sa.Column('notification_method_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('notifications_histories_ibfk_2', 'notifications_histories', 'notifications_methods', ['notification_method_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
