"""empty message

Revision ID: cdd206efba59
Revises: 981f5948ca55
Create Date: 2024-07-26 18:04:22.388621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cdd206efba59'
down_revision: Union[str, None] = '981f5948ca55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_settings', sa.Column('is_system_email', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_system_telegram', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_system_push', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_request_email', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_request_telegram', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_request_push', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_requisite_email', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_requisite_telegram', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_requisite_push', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_chat_email', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_chat_telegram', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_chat_push', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_transfer_email', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_transfer_telegram', sa.Boolean(), nullable=True))
    op.add_column('notifications_settings', sa.Column('is_transfer_push', sa.Boolean(), nullable=True))
    op.drop_column('notifications_settings', 'is_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications_settings', sa.Column('is_order', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('notifications_settings', 'is_transfer_push')
    op.drop_column('notifications_settings', 'is_transfer_telegram')
    op.drop_column('notifications_settings', 'is_transfer_email')
    op.drop_column('notifications_settings', 'is_chat_push')
    op.drop_column('notifications_settings', 'is_chat_telegram')
    op.drop_column('notifications_settings', 'is_chat_email')
    op.drop_column('notifications_settings', 'is_requisite_push')
    op.drop_column('notifications_settings', 'is_requisite_telegram')
    op.drop_column('notifications_settings', 'is_requisite_email')
    op.drop_column('notifications_settings', 'is_request_push')
    op.drop_column('notifications_settings', 'is_request_telegram')
    op.drop_column('notifications_settings', 'is_request_email')
    op.drop_column('notifications_settings', 'is_system_push')
    op.drop_column('notifications_settings', 'is_system_telegram')
    op.drop_column('notifications_settings', 'is_system_email')
    # ### end Alembic commands ###
