"""empty message

Revision ID: cea2dd38e12b
Revises: 1dd1fbb1857d
Create Date: 2024-07-23 17:42:10.274531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea2dd38e12b'
down_revision: Union[str, None] = '1dd1fbb1857d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_read')
    # ### end Alembic commands ###
